---
title: "Manuel Mares Tarea 3   Importaciones totales y AMZN" 
name: "Jesús Leonardo Villanueva Barrón"
lang: es
format:
  html:
    grid:
      body-width: 1200px 
---

Instalar las bibliotecas: `openpyxl`, `datetime`, `plotly` y `statsmodels`; para manejar archivos Excel, trabajar con fechas, crear gråficos interactivos y realizar anålisis de series temporales, respectivamente. Agregar tambiÊn la extension `Data Wrangler` para facilitar la manipulación de datos en `pandas`.


```{python}
#| echo: false

import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import pandas as pd

import matplotlib.ticker as ticker
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import calendar
import statsmodels.api as sm
import statsmodels.graphics.tsaplots as tsaplots
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.seasonal as seasonal
```


## Indicadores Económicos del INEGI


**Cargar datos**

Cargo el conjunto de datos y mostramos su estructura para entender quÊ tipo de información contiene y cómo estå organizada. Esto nos permitirå seleccionar las columnas relevantes para nuestras gråficas de series temporales.

```{python}
#| code-fold: true

data_inegi = pd.read_excel("TIE_Inegi_long.xlsx")
data_inegi.info()
```



### Importaciones totales

En esta sección, se grafica la serie temporal de las importaciones totales para observar su evolución a lo largo del tiempo. Esto puede ayudar a identificar tendencias, patrones estacionales o cambios significativos en el número de importaciones, lo que es crucial para el anålisis económico y la toma de decisiones en políticas comerciales o estrategias empresariales.


```{python}
#| code-fold: true
df_importaciones = data_inegi[["Fecha", "Importaciones_totales"]].dropna()
df_importaciones.info()
print(f"Fecha de inicio: {df_importaciones['Fecha'].min()}")
print(f"Fecha de fin: {df_importaciones['Fecha'].max()}")
print("------")

print("Estadísticas descriptivas de Importaciones Totales:")
print(df_importaciones["Importaciones_totales"].describe())
```



**Serie temporal de las importaciones totales**

Una serie temporal es una secuencia de datos recopilados o registrados en intervalos de tiempo sucesivos. En este caso, se grafican las importaciones totales a lo largo del tiempo para visualizar su evolución y detectar posibles tendencias o patrones en el mercado comercial.


```{python}
#| code-fold: true

# Configurar la columna "Fecha" como índice para facilitar la manipulación de datos y la creación de gråficos de series temporales.
df_importaciones.set_index("Fecha", inplace=True)
# Definición de la serie temporal
importaciones_ts = df_importaciones["Importaciones_totales"]
print(importaciones_ts.info())
```


**Gråfica de la serie temporal de Importaciones Totales**

```{python}
#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
plt.plot(importaciones_ts.index, importaciones_ts.values, marker='o', ms=3)
plt.title('Importaciones_totales')
plt.xlabel('Fecha')
plt.ylabel('Importaciones_totales')
plt.grid(alpha=0.3)
plt.show()
```

Filtramos datos a partir de 2016 para observar mejor la tendencia en los últimos aùos.

```{python}
#| code-fold: true
#| fig-align: "center"
importaciones_ts_2016 = importaciones_ts[importaciones_ts.index >= "2016-01-01"]
plt.figure(figsize=(12, 6))
plt.plot(importaciones_ts_2016.index, importaciones_ts_2016.values, marker='o', ms=5)
plt.title('Importaciones_totales (Desde 2016)')
plt.xlabel('Fecha')
plt.ylabel('Importaciones_totales')
plt.grid(alpha=0.3)
plt.show()
```


**Gråfica interactiva de la serie temporal de Importaciones Totales**


```{python}
#| code-fold: true
#| fig-align: "center"


fig = px.line(x = importaciones_ts_2016.index, y = importaciones_ts_2016.values, title='Importaciones Totales', labels={'y': 'Importaciones_totales', 'x': 'Fecha'})
fig.update_xaxes(rangeslider_visible=True)
```


**Comparación anual Importaciones Totales**


```{python}
#| code-fold: true
#| fig-align: "center"

# Preparación de datos para la gråfica de comparación anual
df_importaciones_anual = importaciones_ts_2016.reset_index()
df_importaciones_anual['Aùo'] = df_importaciones_anual['Fecha'].dt.year
df_importaciones_anual['Mes'] = df_importaciones_anual['Fecha'].dt.month
df_importaciones_anual["Nombre_mes"] = df_importaciones_anual['Fecha'].dt.strftime('%b')


plt.figure(figsize=(12, 6))
sns.lineplot(data=df_importaciones_anual, x='Nombre_mes', y='Importaciones_totales', hue='Aùo', marker='o', palette='tab10')
plt.title('Comparación Anual de Importaciones_totales')
plt.xlabel('Mes')
plt.ylabel('Número de Importaciones_totales')
plt.legend(title='Aùo', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```

**Comparación mensual de Importaciones Totales**




```{python}
#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
sns.lineplot(data=df_importaciones_anual, x='Aùo', y='Importaciones_totales', hue='Nombre_mes', marker='o', palette='tab10')
plt.title('Comparación Mensual de Importaciones_totales')
plt.xlabel('Aùo')
plt.ylabel('Número de Importaciones_totales')
plt.legend(title='Mes', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```




```{python}
#| code-fold: true
#| fig-align: "center"

fig = px.line(df_importaciones_anual, x='Aùo', y='Importaciones_totales', markers=True, color='Nombre_mes', title='Comparación Mensual de Importaciones_totales', labels={'Importaciones_totales': 'Número de Importaciones_totales'})
fig.update_layout(legend_title_text='Mes', plot_bgcolor='rgba(194, 190, 190, 0)', xaxis=dict(tickmode='linear'))
fig.update
fig.update_xaxes(dtick=1, gridcolor='rgba(138, 132, 132, 0.77)')
fig.update_yaxes(gridcolor='rgba(138, 132, 132, 0.77)')

```


**Boxplot trimestral de la serie temporal de Importaciones Totales**

Con esta gråfica, se busca visualizar la distribución de las importaciones totales en cada trimestre a lo largo de los aùos. Esto permite identificar patrones estacionales, variabilidad y posibles outliers en los datos trimestrales, lo que es útil para el anålisis económico y la toma de decisiones estratÊgicas.


```{python}
#| code-fold: true
#| fig-align: "center"

df_importaciones_anual['Trimestre'] = df_importaciones_anual['Fecha'].dt.to_period('Q')

# Variable combinada de aùo y trimestre para el eje x
df_importaciones_anual['Aùo_Trimestre'] = df_importaciones_anual['Aùo'].astype(str) + '-Q' + df_importaciones_anual['Trimestre'].dt.quarter.astype(str)

plt.figure(figsize=(12, 6))
sns.boxplot(data=df_importaciones_anual, x='Aùo_Trimestre', y='Importaciones_totales', hue='Aùo', palette= 'Paired')
plt.title('Boxplot Trimestral de Importaciones Totales')
plt.xlabel('Aùo-Trimestre')
plt.ylabel('Número de Importaciones_totales')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.legend(title='Aùo', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()


```


**Heatmap importaciones totales**


```{python}
#| code-fold: true
#| fig-align: "center"

# Preparación de datos para el heatmap
heatmap_data = df_importaciones_anual.pivot_table(index='Mes', columns='Aùo', values='Importaciones_totales')

plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, annot=True, linewidths=0.5, fmt=".1e", cmap='Spectral')
plt.title('Heatmap de Importaciones Totales por Mes y Aùo')
plt.xlabel('Aùo')
plt.ylabel('Mes')
plt.yticks(ticks = np.linspace(0.5, 11.5, 12), labels=[calendar.month_abbr[i] for i in range(1, 13)], rotation=0)
plt.show()
```


**Superficie importaciones totales**

```{python}
#| code-fold: true
#| fig-align: "center"

Z = heatmap_data.values
X = heatmap_data.columns.astype(str) #Aùos
Y = calendar.month_abbr[1:13] #Meses

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, 
                contours=dict(
        x=dict(
            show=True,          # Líneas por aùo sobre la superficie
            color="white",
            width=2
        ),
        y=dict(
            show=True,          # Líneas por mes sobre la superficie
            color="white",
            width=2
        )
    ),
                colorscale='Spectral')])
fig.update_layout(title='Superficie de Importaciones Totales',
                  scene=dict(xaxis_title='Aùo', yaxis_title='Mes', zaxis_title='Número de Importaciones_totales'),
                  autosize=True,
                  height=600)
```


**Descomposición de la serie temporal de las Importaciones Totales**

Una serie temporal $Y_t$ se puede descomponer en tres componentes principales: tendencia ($T_t$), estacionalidad ($S_t$) y ruido o componente aleatorio ($R_t$). La fórmula general para la descomposición aditiva es:

\begin{equation}
Y_t = T_t + S_t + R_t
\end{equation}

TambiÊn existe la descomposición multiplicativa, que se expresa como:

\begin{equation}
Y_t = T_t \times S_t \times R_t
\end{equation}


**Descomposición aditiva de la serie temporal de las Importaciones Totales**

```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición aditiva de la serie temporal de las Importaciones Totales"

decomposition_add = seasonal.seasonal_decompose(importaciones_ts_2016, model='additive', period=12)

plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(importaciones_ts_2016,color='blue')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_add.trend,color='orange')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_add.seasonal,color='green')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_add.resid,color='red')
plt.title('Ruido')
plt.tight_layout()
plt.show()

```


**Descomposición multiplicativa de la serie temporal de las Importaciones Totales**

```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición multiplicativa de la serie temporal de las Importaciones Totales"

decomposition_mul = seasonal.seasonal_decompose(importaciones_ts_2016, model='multiplicative', period=12)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(importaciones_ts_2016,color='blue')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_mul.trend,color='orange')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_mul.seasonal,color='green')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_mul.resid,color='red')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

## Valores financieros

En esta sección, se analiza la serie temporal de los precios de las acciones de Amazon (AMZN) y usare datos descargados de Yahoo Finance. Se visualizan los precios a lo largo del tiempo, se comparan anualmente y mensualmente, y se realiza una descomposición de la serie temporal para identificar sus componentes de tendencia, estacionalidad y ruido. Esto permite comprender mejor el comportamiento de las acciones de AMZN y tomar decisiones informadas basadas en su evolución histórica.

```{python}
#| code-fold: true
#| fig-align: "center"

tickers = ["AMZN", "AAPL", "MSFT", "GOOGL", "META"]
start_date = "2020-01-01"
end_date = "2025-12-31"

df_yf = yf.download(tickers, start=start_date, end=end_date, interval="1d")["Close"]
```

**Gråfica de los precios de las acciones**

```{python}
#| code-fold: true
#| fig-align: "center"

fig = go.Figure()
for ticker in tickers:
    fig.add_trace(go.Scatter(x=df_yf.index, y=df_yf[ticker], name=ticker))
fig.update_layout(title='Precios de las acciones (2020-2025)', xaxis_title='Fecha', yaxis_title='Precio (USD)', legend_title_text='Acciones', hovermode='x unified')
fig.update_xaxes(rangeslider_visible=True, gridcolor='rgba(138, 132, 132, 0.77)')
fig.update_yaxes(gridcolor='rgba(138, 132, 132, 0.77)')
fig.show()  
```


```{python}
print(type(df_yf))
print(df_yf.columns.tolist())
print(df_yf.head(2))
```


Ahora seleccionamos la acción de AMZN para realizar un anålisis mås detallado de su serie temporal, incluyendo la descomposición de la serie temporal para identificar sus componentes de tendencia, estacionalidad y ruido.

**Candlestick de AMZN**

```{python}
#| code-fold: true
#| fig-align: "center"

df_amzn_ohlc = yf.download("AMZN", start='2025-11-01', end='2025-12-31', interval="1d")
amzn = df_amzn_ohlc.xs("AMZN", level=1, axis=1)

fig = go.Figure(data=[go.Candlestick(x=amzn.index,
                open=amzn['Open'],
                high=amzn['High'],
                low=amzn['Low'],
                close=amzn['Close'])])
fig.update_layout(title='Gråfico de Velas de AMZN (2020-2025)', xaxis_title='Fecha', yaxis_title='Precio (USD)')
fig.update_xaxes(rangeslider_visible=True, gridcolor='rgba(138, 132, 132, 0.77)')
fig.update_yaxes(gridcolor='rgba(138, 132, 132, 0.77)')
fig.show()
```



**Resumen estadístico de los precios de AMZN**

```{python}
#| code-fold: true

amzn_ts = df_yf["AMZN"].dropna()
print(amzn_ts.info())
print(f"Fecha de inicio: {amzn_ts.index.min()}")
print(f"Fecha de fin: {amzn_ts.index.max()}")
print("------")
print("Estadísticas descriptivas de AMZN:")
print(amzn_ts.describe())

```

**Comparación anual de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"

amzn_df = amzn_ts.reset_index()
amzn_df['Aùo'] = amzn_df['Date'].dt.year
amzn_df['Mes'] = amzn_df['Date'].dt.month
amzn_df["Nombre_mes"] = amzn_df['Date'].dt.strftime('%b')
amzn_df['Dia_aùo']   = amzn_df['Date'].dt.dayofyear 

plt.figure(figsize=(12, 6))
sns.lineplot(data=amzn_df, x='Nombre_mes', y='AMZN', hue='Aùo', marker='o', palette='tab10')
plt.title('Comparación Anual de AMZN (Mensual)')
plt.xlabel('Mes')
plt.ylabel('Precio (USD)')
plt.legend(title='Aùo', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()
```




```{python}
#| code-fold: true
#| fig-align: "center"

#| code-fold: true
#| fig-align: "center"

plt.figure(figsize=(12, 6))
sns.lineplot(
    data=amzn_df,
    x='Dia_aùo',
    y='AMZN',
    hue='Aùo',
    palette='tab10',
    errorbar=None
)

# Reemplazar números de día por nombres de mes en el eje X

meses_dias = [1, 32, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335]
meses_nombres = ['Ene','Feb','Mar','Abr','May','Jun',
                 'Jul','Ago','Sep','Oct','Nov','Dic']
plt.xticks(ticks=meses_dias, labels=meses_nombres)

plt.title('Comparación Anual de AMZN (Diaria)')
plt.xlabel('Mes')
plt.ylabel('Precio (USD)')
plt.legend(title='Aùo', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()
```


**Boxplot trimestral de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"


amzn_df['Trimestre'] = amzn_df['Date'].dt.to_period('Q')
amzn_df['Aùo_Trimestre'] = amzn_df['Aùo'].astype(str) + '-Q' + amzn_df['Trimestre'].dt.quarter.astype(str)

plt.figure(figsize=(12, 6))
sns.boxplot(data=amzn_df, x='Aùo_Trimestre', y='AMZN', hue='Aùo', palette= 'Paired')
plt.title('Boxplot Trimestral de AMZN')
plt.xlabel('Aùo-Trimestre')
plt.ylabel('Precio (USD)')
plt.xticks(rotation=45)
plt.grid(alpha=0.3)
plt.legend(title='Aùo', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()
```

**Heatmap de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"


#| code-fold: true
#| fig-align: "center"

# Crear columna de día del aùo para ordenar correctamente
amzn_df['Mes-dia']  = amzn_df['Date'].dt.strftime('%b-%d')


heatmap_data_amzn = amzn_df.pivot_table(
    index='Mes-dia',
    columns='Aùo',
    values='AMZN'
)

# Ordenar por día del aùo (no alfabÊticamente)
orden = (amzn_df.drop_duplicates('Mes-dia')
                 .sort_values('Dia_aùo')['Mes-dia']
                 .tolist())
heatmap_data_amzn = heatmap_data_amzn.reindex(orden)

# Rellenar NaN para eliminar líneas blancas
heatmap_data_amzn = heatmap_data_amzn.ffill().bfill()

plt.figure(figsize=(12, 8))
sns.heatmap(
    heatmap_data_amzn,
    annot=False,
    cmap='Spectral',
    linewidths=0,        
    linecolor='none'     
)
plt.title('Heatmap de AMZN por Fecha y Aùo')
plt.xlabel('Aùo')
plt.ylabel('Fecha')

plt.tight_layout()
plt.show()
```


**Superficie de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"

Z = heatmap_data_amzn.values
X = heatmap_data_amzn.columns.astype(str) #Aùos
Y = heatmap_data_amzn.index #Fechas

fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, 
                contours=dict(
        x=dict(
            show=True,          # Líneas por aùo sobre la superficie
            color="white",
            width=2
        ),
        y=dict(
            show=True,          # Líneas por fecha sobre la superficie
            color="white",
            width=2
        )
    ),
                colorscale='Spectral')])
fig.update_layout(title='Superficie de AMZN', scene=dict(xaxis_title='Aùo', yaxis_title='Fecha', zaxis_title='Precio (USD)'), autosize=True, height=600)
```

**Descomposición aditiva de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición aditiva de la serie temporal de AMZN"


# Utilizar periodo de 252 para capturar la estacionalidad anual en datos diarios (252 días håbiles por aùo que es el eståndar en finanzas)
decomposition_add_amzn = seasonal.seasonal_decompose(amzn_ts, model='additive', period=252)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(amzn_ts,color='blue')
plt.title('Serie Temporal Original')    

plt.subplot(4,1,2)
plt.plot(decomposition_add_amzn.trend,color='orange')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_add_amzn.seasonal,color='green')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_add_amzn.resid,color='red')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

**Descomposición multiplicativa de AMZN**


```{python}
#| code-fold: true
#| fig-align: "center"
#| fig-cap: "Descomposición multiplicativa de la serie temporal de AMZN"

decomposition_mul_amzn = seasonal.seasonal_decompose(amzn_ts, model='multiplicative', period=252)
plt.figure(figsize=(12, 8))
plt.subplot(4,1,1)
plt.plot(amzn_ts,color='blue')
plt.title('Serie Temporal Original')

plt.subplot(4,1,2)
plt.plot(decomposition_mul_amzn.trend,color='orange')
plt.title('Tendencia')

plt.subplot(4,1,3)
plt.plot(decomposition_mul_amzn.seasonal,color='green')
plt.title('Estacionalidad')

plt.subplot(4,1,4)
plt.plot(decomposition_mul_amzn.resid,color='red')
plt.title('Ruido')
plt.tight_layout()
plt.show()
```

